### ISSUE TITLE
Unidades de transporte

### ISSUE THREAD

**Issue by AnthonyWRodriguez** [FruitParty/Proyecto_Transporte_Escolar_Bonilla#11]
Cuando se le da mantenimiento y despues modificar unidades, aun queda expuesto el boton de agregar mantenimiento

**Comment by FruitParty** [comment]
No entiendo esto

**Comment by LidiaMejia** [comment]
A mi ya no me aparece

**Comment by AnthonyWRodriguez** [comment]
Ya nada, yo vi mal
