### ISSUE TITLE
Pagos

### ISSUE THREAD

**Issue by LidiaMejia** [FruitParty/Proyecto_Transporte_Escolar_Bonilla#19]
- No está adecuado para Viajes.

- Si se quiere realizar el pago de un Contrato Temporal con un solo pago, sale Monto Total 0 y en Monto Mensual sale la cantidad total del contrato. Además, deja pagar varias veces cada mes que dure el contrato, cuando debería ser un solo pago.

**Comment by AnthonyWRodriguez** [comment]
Creo que lo que deberia decir es "Monto por cancelar", e igual es mas util saber cuanto le debe una empresa a cuanto costó el contrato, en todo caso, ocupariamos una nueva columna en SQL, una de valor original y otra de valor por cancelar
