### ISSUE TITLE
Correo Nuevo Empleado

### ISSUE THREAD

**Issue by LidiaMejia** [FruitParty/Proyecto_Transporte_Escolar_Bonilla#23]
Al ingresar un nuevo empleado, y después querer ingresar otro, no deja ya que el correo siempre es erróneo.

**Comment by AnthonyWRodriguez** [comment]
No era el correo, era que el tiempo se igualaba de una manera u otra al tiempo actual, por lo que no entraba por eso. Creo que ya esta arreglado
