### ISSUE TITLE
Error Contrato - Modificar Contratos

### ISSUE THREAD

**Issue by LidiaMejia** [FruitParty/Proyecto_Transporte_Escolar_Bonilla#6]
Si al entrar a la pestaña de Modificar Contrato se da clic directamente a Seleccionar, tira un error del catch

**Comment by AnthonyWRodriguez** [comment]
Ya lo corrijo

**Comment by AnthonyWRodriguez** [comment]
Arreglado y agregado que tambien ocupe seleccionar una celda para modificar los datos de algun contrato (es decir, que esta enabled false en boton antes de seleccionar algo)
